### PR TITLE
10344 Consolidate and update dotNetZip versions

### PR DESCRIPTION
**Pull request by kriswest**
Updating dotNetZip dependency to latest stable, also see: https://github.com/ChartIQ/finsemble-dll/pull/6

### CODE REVIEW

**Comment by kriswest** [comment]
Confirmed that you get the same behaviour with master - and after debugging I think the issue with the Authentication Example is in Finsemble as I can see the messages being sent on the IAB but not picked up/responded to

**Comment by kriswest** [comment]
Re: WindowlessExample - I think it pushes a log message once its up. Thats
about all.

K


Kris West
Senior Solutions Architect
p: +1 800 821 8147  m: +44 (0)7715104292
w: www.chartiq.com  e: kris@chartiq.com

**Comment by thorsent** [comment]
@kriswest @sgd2z need conflicts resolved.

**Comment by kriswest** [comment]
@thorsent conflicts resolved

**Pull request merged**
